### ISSUE TITLE
Pretrained models: problem with direct download in 5.1.

### ISSUE THREAD

**Issue by Goschjann** [Goschjann/mrk_dl_showcase#2]
Workaround: model weights stored in `./models/...h5` and called from within the notebook. 

Is that cool? Will that work within MR?

**Comment by ja-thomas** [comment]
Can you explain the problem? I'm not sure I understand

You "cache" the weights in the repository instead of downloading them on the fly?

**Comment by Goschjann** [comment]
all good, solved!
